<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>MageGameScript</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#serial_settings_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#dialog_settings_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#dialog_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#serial_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#script_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#var_node</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment_node</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_block</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment_inline</string>
          </dict>
        </array>
      </dict>
      <key>comment_block</key>
      <dict>
        <key>begin</key>
        <string>/\*</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\*/</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.block.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>.+?</string>
          </dict>
        </array>
      </dict>
      <key>comment_inline</key>
      <dict>
        <key>begin</key>
        <string>//</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>
|$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>comment.line.double-slash.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>.+?</string>
          </dict>
        </array>
      </dict>
      <key>serial_settings_node</key>
      <dict>
        <key>begin</key>
        <string>(settings)(\s+for)?\s+(serial)(\s+dialog)?\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_wrap</string>
          </dict>
        </array>
      </dict>
      <key>dialog_settings_node</key>
      <dict>
        <key>begin</key>
        <string>(settings)(\s+for)?\s+(dialog)\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_settings_individual_parameters_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_settings_global_parameters_node</string>
          </dict>
        </array>
      </dict>
      <key>dialog_settings_individual_parameters_node</key>
      <dict>
        <key>begin</key>
        <string>\b(parameters)(\s+for)?\s+(label|entity)\s+(([^\s'"]+)|(['"])[^`]*?\6)\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.type.mgs</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_parameter</string>
          </dict>
        </array>
      </dict>
      <key>dialog_settings_global_parameters_node</key>
      <dict>
        <key>begin</key>
        <string>\b(parameters\s+)?(for\s+)?(global\s+)?(defaults?)?\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_parameter</string>
          </dict>
        </array>
      </dict>
      <key>generic_numberish</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>#[0-9A-F]+\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+(s|ms|px|pix|x)?|once|twice|thrice)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
        </array>
      </dict>
      <key>generic_var</key>
      <dict>
        <key>match</key>
        <string>\$[-A-Za-z0-9_.#$]+\b</string>
        <key>name</key>
        <string>variable.other.constant.mgs</string>
      </dict>
      <key>generic_string_naive</key>
      <dict>
        <key>match</key>
        <string>[-A-Za-z0-9_.#$]+|(['"])[^`]*?\1</string>
        <key>name</key>
        <string>string.variable.mgs</string>
      </dict>
      <key>generic_bool</key>
      <dict>
        <key>match</key>
        <string>\b(true|false|on|off|glitched|unglitched)\b</string>
        <key>name</key>
        <string>constant.language.mgs</string>
      </dict>
      <key>var_node</key>
      <dict>
        <key>begin</key>
        <string>\b(const!)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>mega.block.mgs punctuation.section.block.end.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>match</key>
            <string>=</string>
            <key>name</key>
            <string>keyword.operator.assignment.mgs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#generic_var</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#generic_numberish</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#generic_bool</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#generic_string_naive</string>
          </dict>
        </array>
      </dict>
      <key>entity_specifier_string_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(entity)\s+(['"])(%PLAYER%|%SELF%)(\2)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(entity)\s+(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(entity)\s+(([-A-Za-z0-9_.#$]+)|(['"])([^`]*?)\4)\s</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>geometry_specifier_string_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(geometry)\s+(['"])(%ENTITY_PATH%)(\2)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(geometry)\s+(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(geometry)\s+(([-A-Za-z0-9_.#$]+)|(['"])([^`]*?)\4)\s</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>name_specifier_string_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(name)\s+(['"])(%[^%]+%)(\2)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(name)\s+(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(name)\s+(([-A-Za-z0-9_.#$]+)|(['"])([^`]*?)\4)\s</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>dialog_misc_specifier_string_pair</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(portrait|border_tileset)\s+(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(portrait|border_tileset)\s+(([-A-Za-z0-9_.#$]+)|(['"])([^`]*?)\4)\s</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>dialog_parameter</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#entity_specifier_string_pair</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#name_specifier_string_pair</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_misc_specifier_string_pair</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=alignment|emote)\s+\$[-A-Za-z0-9_.#$]+\b</string>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\balignment)\s+(TR|BR|TL|BL|TOP_RIGHT|BOTTOM_RIGHT|TOP_LEFT|BOTTOM_LEFT)\b</string>
            <key>name</key>
            <string>constant.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(entity|name|portrait|alignment|border_tileset|emote)\b</string>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(wrap)(\s+messages)(\s+to)?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>dialog_option_goto</key>
      <dict>
        <key>match</key>
        <string>(:)\s*(goto\s)?(script\s)?(((['"])[^`]*?\6)|[-A-Za-z0-9_.#$]+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
        </dict>
      </dict>
      <key>dialog_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_head</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_message</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_option_goto</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&gt;|:</string>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
        </array>
      </dict>
      <key>dialog_message</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)(?:\\{2})*\K"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.character.escape.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[nt"$%\\]</string>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[%][^%]+?[%]</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$[^\$]+?\$</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>string.variable.mgs</string>
          </dict>
        </array>
      </dict>
      <key>serial_message</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)(?:\\{2})*\K"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.character.escape.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&lt;)(((/|reset)|bold|dim|(bg-)?(black|red|green|yellow|blue|magenta|cyan|white|k|r|g|y|b|m|c|w)))(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.mgs</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[nt"\\]</string>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$[^\$]+?\$</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>string.variable.mgs</string>
          </dict>
        </array>
      </dict>
      <key>serial_message_underscore</key>
      <dict>
        <key>begin</key>
        <string>(_)\s+(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)(?:\\{2})*\K"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.character.escape.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[t"\\]</string>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>string.variable.mgs</string>
          </dict>
        </array>
      </dict>
      <key>set_serial_connect_node</key>
      <dict>
        <key>begin</key>
        <string>\b(set)(\s+serial\s+connect(\s+message)?)(\s+to)?(\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\8)))?\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#serial_body</string>
          </dict>
        </array>
      </dict>
      <key>show_serial_node</key>
      <dict>
        <key>begin</key>
        <string>\b(show|concat)\s+(serial\s+dialog)(\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\6)))?\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#serial_body</string>
          </dict>
        </array>
      </dict>
      <key>serial_node</key>
      <dict>
        <key>begin</key>
        <string>\b(serial\s+dialog)(\s+([-A-Za-z0-9_.#$]+|(['"])[^`]*?\4))\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#serial_body</string>
          </dict>
        </array>
      </dict>
      <key>serial_wrap</key>
      <dict>
        <key>match</key>
        <string>\b(wrap)(\s+messages)?(\s+to)?\s+((\$[-A-Za-z0-9_.#$]+)|([0-9]+))\b</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
        </dict>
      </dict>
      <key>serial_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_wrap</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_message</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_message_underscore</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_option_goto</string>
          </dict>
          <dict>
            <key>match</key>
            <string>_|:|#</string>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
        </array>
      </dict>
      <key>show_dialog_node</key>
      <dict>
        <key>begin</key>
        <string>\b(show)\s+(dialog)(\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\6)))?\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs string.variable.mgs</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#dialog_body</string>
          </dict>
        </array>
      </dict>
      <key>dialog_node</key>
      <dict>
        <key>begin</key>
        <string>\b(dialog)(\s+([-A-Za-z0-9_.#$]+|(['"])[^`]*?\4))\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#dialog_body</string>
          </dict>
        </array>
      </dict>
      <key>dialog_head</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_head_entity</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_head_name</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_head_simple</string>
          </dict>
        </array>
      </dict>
      <key>dialog_head_entity</key>
      <dict>
        <key>begin</key>
        <string>entity\s+((\$[-A-Za-z0-9_.#$]+\b)|[-0-9A-Za-z_$#]+\b|(['"])((%PLAYER%|%SELF%)|[^`]*?)\3)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=")</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_parameter</string>
          </dict>
        </array>
      </dict>
      <key>dialog_head_name</key>
      <dict>
        <key>begin</key>
        <string>name\s+((\$[-A-Za-z0-9_.#$]+\b)|[-0-9A-Za-z_$#]+\b|(['"])((%[^%]+%)|[^`]*?)\3)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=")</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_parameter</string>
          </dict>
        </array>
      </dict>
      <key>dialog_head_simple</key>
      <dict>
        <key>begin</key>
        <string>((\$[-A-Za-z0-9_.#$]+)|(\b[-0-9A-Za-z_$#]+))\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.type.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?=")</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_parameter</string>
          </dict>
        </array>
      </dict>
      <key>if_then</key>
      <dict>
        <key>begin</key>
        <string>\bif\b</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\bthen\b|\n</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#conditions</string>
          </dict>
        </array>
      </dict>
      <key>conditions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#condition_subjects</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#condition_predicates</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#condition_compounds</string>
          </dict>
        </array>
      </dict>
      <key>condition_compounds</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(interact_script|tick_script|look_script)(\s+is(\s+not)?)\s+([-A-Za-z0-9_.#$]+|(['"])[^`]*?\5)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(direction)\s+(is\s+(not\s+)?)((north|south|east|west)|(\$[-A-Za-z0-9_.#$]+))\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.language.mgs</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(path)\s+(is\s+(not\s+)?)(['"])(%ENTITY_PATH%)(\4)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(name|type|entity_type|path|warp\s+state)\s+(is\s+(not\s+)?)((\$[-A-Za-z0-9_.#$]+)|([-A-Za-z0-9_.#$]+)|(['"])[^`]*?\7)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(x|y|primary_id|secondary_id|primary_id_type|animation|animation_frame|hackable_state_a|hackable_state_b|hackable_state_c|hackable_state_d|hackable_state_au2|hackable_state_cu2|hackable_state_au4)(\s+is(\s+not)?)\s+((\$[-A-Za-z0-9_.#$]+)|([0-9]+))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>condition_subjects</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(button|flag|variable|geometry)\s+(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(button)(\s+(MEM0|MEM1|MEM2|MEM3|BIT128|BIT64|BIT32|BIT16|BIT8|BIT4|BIT2|BIT1|XOR|ADD|SUB|PAGE|LJOY_CENTER|LJOY_UP|LJOY_DOWN|LJOY_LEFT|LJOY_RIGHT|RJOY_CENTER|RJOY_UP|RJOY_DOWN|RJOY_LEFT|RJOY_RIGHT|TRIANGLE|X|CROSS|CIRCLE|O|SQUARE|HAX|ANY))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#entity_specifier_string_pair</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(flag|variable|geometry)\s+((([-A-Za-z0-9_.#$]+\b)|(['"])[^`]*?\5))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>condition_predicates</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(is(\s+not)?)\s+(true|false|on|off|glitched|unglitched)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(is(\s+not)?)\s+(currently\s+pressed|inside)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(is(\s+not)?)\s+*((==|&lt;=|&lt;|&gt;|&gt;=)\s*)?([0-9]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(is(\s+not)?)\s*((==|&lt;=|&lt;|&gt;|&gt;=)\s*)?(\$[-A-Za-z0-9_.#$]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(is(\s+not)?)\s*((==|&lt;=|&lt;|&gt;|&gt;=)\s*)?([-A-Za-z0-9_.#$]+\b|(['"])[^`]*?\6)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>zigzag</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#zigzag_condition</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#zigzag_else_body</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#zigzag_body</string>
          </dict>
        </array>
      </dict>
      <key>zigzag_condition</key>
      <dict>
        <key>begin</key>
        <string>\b(if|else\s+if)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>meta.parens.mgs punctuation.section.parens.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>meta.parens.mgs punctuation.section.parens.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#conditions</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\|\|</string>
            <key>name</key>
            <string>keyword.operator.logical.mgs</string>
          </dict>
        </array>
      </dict>
      <key>zigzag_body</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#zigzag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
      <key>zigzag_else_body</key>
      <dict>
        <key>begin</key>
        <string>\belse\s+(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>keyword.control.conditional.mgs</string>
          </dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
      <key>script_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#zigzag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#if_then</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#show_dialog_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#set_serial_connect_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#show_serial_node</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>SCRIPT STRINGS</string>
            <key>match</key>
            <string>\b(then\s+)?(goto)(\s+script(?!-))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(copy)\s+(?=(entity|geometry|flag|variable|map))</string>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>SCRIPT STRINGS</string>
            <key>match</key>
            <string>\b(copy)(\s+script(?!-))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(-&gt;)(\s*script\b)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>comment</key>
            <string>SCRIPT STRINGS</string>
            <key>match</key>
            <string>(?&lt;=goto|copy|script|-&gt;)\s+(((['"])[^`]*?\3)|[-A-Za-z0-9_.#$]+\b)</string>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.control.mgs</string>
            <key>match</key>
            <string>\b(load)\s*(?=map)\b</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(mutate)\s+((\$[-A-Za-z0-9_.#$]+)|([-A-Za-z0-9_.#$]+|(['"])[^`]*?\5))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(wait|block)\s+((\$[-A-Za-z0-9_.#$]+)|([0-9]+(ms|s)?))\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(save)(\s+slot)?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(make|walk|loop|turn|rotate|teleport|pan|loop|play|set|fade\s+in|fade\s+out|load|erase|open|close|wait|block|shake)\b</string>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#entity_specifier_string_pair</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#geometry_specifier_string_pair</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(fail(ure)?|animation|camera|(player|serial)\s+control|hex(\s+(dialog\s+mode|control|clipboard|editor))?)\b</string>
            <key>name</key>
            <string>variable.parameter.mgs support.variable.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(to\s+)?((true|false|on|off|glitched|unglitched)|(\$[-A-Za-z0-9_.#$]+))\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(north|south|east|west)\b</string>
            <key>name</key>
            <string>constant.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(name|type|path|warp\s+state)(\s+to)?\s+((\$[-A-Za-z0-9_.#$]+)|[-A-Za-z0-9_.#$]+|(['"])[^`]*?\5)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(interact_script|tick_script)(\s+to)?\s+((\$[-A-Za-z0-9_.#$]+)|[-A-Za-z0-9_.#$]+|(['"])[^`]*?\5)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(x|y|primary_id|secondary_id|primary_id_type|animation|animation_frame|hackable_state_a|hackable_state_b|hackable_state_c|hackable_state_d|hackable_state_au2|hackable_state_cu2|hackable_state_au4)(\s+to)?\s+(([0-9]]+)|(\$[-A-Za-z0-9_.#$]+))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(slot)\s+(([0-2])|([0-9]+)|(\$[-A-Za-z0-9_.#$]+))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>invalid.illegal.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(to|from)\s+((#[0-9A-F]+|black|white)|(\$[-A-Za-z0-9_.#$]+))?\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#generic_numberish</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(along|follow|toward|from|into|over|for)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(map\s+tick_script)(\s+to)?\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\5))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(serial\s+connect(\s+message)?)(\s+to)?\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\6))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(flag|map|variable|(serial\s+)?dialog)\s+((\$[-A-Za-z0-9_.#$]+)|([-A-Za-z0-9_.#$]+\b)|(['"])[^`]*?\6)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((un)?register)(\s+command)?\s+((\$[-A-Za-z0-9_.#$]+)|([-A-Za-z0-9_.#$]+\b)|(['"])[^`]*?\7)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+\s*)(arg\s+)((\$[-A-Za-z0-9_.#$]+)|[-A-Za-z0-9_.#$]+|(['"])[^`]*?\5)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(\+\s*)(arg\s+)?((\$[-A-Za-z0-9_.#$]+)|[-A-Za-z0-9_.#$]+|(['"])[^`]*?\5)?\s*(?=-&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(SET|ADD|SUB|MUL|DIV|MOD|RNG|set|add|sub|mul|div|mod|rng|=|\+|-|\*|\/|%|\?)\s+(([0-9]+)|(\$[-A-Za-z0-9_.#$]+))\s*(?!-&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>constant.numeric.integer.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(SET|ADD|SUB|MUL|DIV|MOD|RNG|set|add|sub|mul|div|mod|rng|=|\+|-|\*|\/|%|\?)\s+([-A-Za-z0-9_.#$]+\b|(['"])[^`]*?\3)\s*(?!-&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(show|concat)\s+((serial\s+)?dialog)\s+(([-A-Za-z0-9_.#$]+|(['"])[^`]*?\6))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b((interact|tick|look)_script)\s+(to\s+)?([-A-Za-z0-9_.#$]+|(['"])[^`]*?\4)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs support.variable.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>script_node</key>
      <dict>
        <key>begin</key>
        <string>(script\s+)?(((([-A-Za-z0-9_.#$]+)|((['"])[^`]*?\7))))\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>mega.block.mgs punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.mgs</string>
  </dict>
</plist>