<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>MageGameScript</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment_node</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#include_macro</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#fn_definition</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(add)(\s+serial_dialog)(\s+settings)(\s*{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.object.property.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_parameters</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(add)(\s+dialog)(\s+settings)(\s*{)?</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.object.property.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(label)\s+([_a-zA-Z][_a-zA-Z0-9]*)\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#dialog_parameter</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(entity)\s+([_a-zA-Z][_a-zA-Z0-9]*|"(%(PLAYER|SELF)%)")\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#dialog_parameter</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(entity)\s+([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*")\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.type.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#dialog_parameter</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(default)\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#dialog_parameter</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(dialog)\s+([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*")\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#dialog_body</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>\b(serial_dialog)\s+([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*")\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#serial_body</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(script\s+)?([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*")\s*({)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>\b=\b</string>
        <key>name</key>
        <string>keyword.operator.assignment.mgs</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant_literal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#number_literal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#boolean_literal</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#language_constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string_literal</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment_node</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.mgs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.block.mgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>
|$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.mgs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>comment.line.double-slash.mgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>.+?</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>number_literal</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>#[0-9A-Fa-f]+\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b([0-9]+(s|ms|px|pix|x)?|once|twice|thrice)\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bblack|white|red|green|blue|magenta|cyan|yellow\b</string>
            <key>name</key>
            <string>constant.numeric.integer.mgs</string>
          </dict>
        </array>
      </dict>
      <key>include_macro</key>
      <dict>
        <key>match</key>
        <string>\b(include)\s*("[^"]+")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.mgs</string>
          </dict>
        </dict>
      </dict>
      <key>constant_literal</key>
      <dict>
        <key>match</key>
        <string>\$[_a-zA-Z0-9]+\b</string>
        <key>name</key>
        <string>variable.other.constant.mgs</string>
      </dict>
      <key>string_literal</key>
      <dict>
        <key>match</key>
        <string>[_a-zA-Z][_a-zA-Z0-9]*|"[^"]*"</string>
        <key>name</key>
        <string>string.quoted.mgs</string>
      </dict>
      <key>boolean_literal</key>
      <dict>
        <key>match</key>
        <string>\b(true|false|off)\b|\bon(?!_)\b</string>
        <key>name</key>
        <string>constant.language.mgs</string>
      </dict>
      <key>language_constants</key>
      <dict>
        <key>match</key>
        <string>\bnorth|south|west|east|MEM(0|1|2|3)|BIT(128|64|32|16|8|4|2|1)|XOR|ADD|SUB|PAGE|(L|R)JOY_(CENTER|UP|DOWN|LEFT|RIGHT)|TRIANGLE|X|CROSS|CIRCLE|O|SQUARE|HAX|ANY|ALL|LED_(XOR|ADD|SUB|PAGE|BIT128|BIT64|BIT32|BIT16|BIT8|BIT4|BIT2|BIT1|MEM0|MEM1|MEM2|MEM3|HAX|USB|SD|ANY)\b</string>
        <key>name</key>
        <string>constant.language.mgs</string>
      </dict>
      <key>fn_definition</key>
      <dict>
        <key>begin</key>
        <string>(fn\s+)?("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*)\s*(\()\s*((\$[_a-zA-Z0-9]+)\s*(,\s+(\$[_a-zA-Z0-9]+))?)?\s*(\))\s*(\{)</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant.mgs</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>name</key>
        <string>punctuation.section.block.end.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
      <key>fn_call</key>
      <dict>
        <key>begin</key>
        <string>("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*)\s*(\()</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>punctuation.section.block.begin.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\)</string>
        <key>name</key>
        <string>punctuation.section.block.end.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(")(%(ENTITY_PATH|SELF|PLAYER|MAP)*%)(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#script_body</string>
          </dict>
        </array>
      </dict>
      <key>entity_identifier_special</key>
      <dict>
        <key>match</key>
        <string>\b(entity)\s+(")(%PLAYER%|%SELF%)(")</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.mgs</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>string.quoted.mgs</string>
          </dict>
        </dict>
      </dict>
      <key>dialog_parameter</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#entity_identifier_special</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(name)\s+(")(%[^%]*%)(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(border_tileset|portrait)\s+("[^`]*"|[_a-zA-Z][_a-zA-Z0-9]*)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(entity|name|portrait|border_tileset|alignment|emote|wrap)\b</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=\balignment)\s+(TR|BR|TL|BL|TOP_RIGHT|BOTTOM_RIGHT|TOP_LEFT|BOTTOM_LEFT)\b</string>
            <key>name</key>
            <string>constant.language.mgs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant_literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number_literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string_literal</string>
          </dict>
        </array>
      </dict>
      <key>dialog_option_goto</key>
      <dict>
        <key>match</key>
        <string>(=)\s*("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
        </dict>
      </dict>
      <key>dialog_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>begin</key>
                <string>entity\s+((\$[_a-zA-Z0-9]+\b)|[-0-9A-Za-z_$#]+\b|(")((%PLAYER%|%SELF%)|[^"]*)")</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.mgs</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.constant.mgs</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mgs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=")</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.block.end.mgs</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#comment_node</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#dialog_parameter</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>name\s+((\$[_a-zA-Z0-9]+\b)|[-0-9A-Za-z_$#]+\b|(")((%[^%]*%)|[^"]*)")</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.mgs</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.constant.mgs</string>
                  </dict>
                  <key>5</key>
                  <dict>
                    <key>name</key>
                    <string>variable.language.mgs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=")</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.block.end.mgs</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#comment_node</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#dialog_parameter</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>begin</key>
                <string>((\$[_a-zA-Z0-9]+)|(\b[-0-9A-Za-z_$#]+))\b</string>
                <key>beginCaptures</key>
                <dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>variable.other.constant.mgs</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>support.type.mgs</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>(?=")</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>punctuation.section.block.end.mgs</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>#comment_node</string>
                  </dict>
                  <dict>
                    <key>include</key>
                    <string>#dialog_parameter</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\\)(?:\\{2})*\K"</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.mgs</string>
              </dict>
            </dict>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\\[nt"$%\\]</string>
                <key>name</key>
                <string>constant.character.escape.mgs</string>
              </dict>
              <dict>
                <key>match</key>
                <string>[%][^%]*?[%]</string>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\$[^\$]+?\$</string>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <dict>
                <key>match</key>
                <string>.+?</string>
                <key>name</key>
                <string>string.variable.mgs</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_option_goto</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&gt;)(\s*\$[_a-zA-Z0-9]+)?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>serial_message</key>
      <dict>
        <key>begin</key>
        <string>"</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)(?:\\{2})*\K"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.character.escape.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(&lt;)(((/|reset|bell)|bold|dim|(bg-)?(black|red|green|yellow|blue|magenta|cyan|white|k|r|g|y|b|m|c|w)))(&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.begin.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.tag.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.mgs</string>
              </dict>
              <key>7</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.tag.end.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\\[nt"\\]</string>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[%][^%]*[%]</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\$[^\$]+?\$</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>string.variable.mgs</string>
          </dict>
        </array>
      </dict>
      <key>serial_message_underscore</key>
      <dict>
        <key>begin</key>
        <string>(_)\s+(")</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(?&lt;!\\)(?:\\{2})*\K"</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>string.quoted.double.mgs</string>
          </dict>
        </dict>
        <key>name</key>
        <string>constant.character.escape.mgs</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\[t"\\]</string>
            <key>name</key>
            <string>constant.character.escape.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>.+?</string>
            <key>name</key>
            <string>string.variable.mgs</string>
          </dict>
        </array>
      </dict>
      <key>serial_parameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\bwrap\b</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant_literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number_literal</string>
          </dict>
        </array>
      </dict>
      <key>serial_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_parameters</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_message</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#serial_message_underscore</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#dialog_option_goto</string>
          </dict>
          <dict>
            <key>match</key>
            <string>_|:|#</string>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
        </array>
      </dict>
      <key>script_body</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comment_node</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(for)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>match</key>
                <string>;</string>
                <key>name</key>
                <string>keyword.operator.logical.mgs</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(do)\s*(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(while)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(if|else\s+if)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.parens.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\belse\s+(\{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment_node</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\bif\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\bthen\b|\n</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.control.conditional.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#fn_call</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(debug\s*!)\s*(\()\s*([_a-zA-Z][_a-zA-Z0-9]*)?\s*(\))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(debug\s*!)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#serial_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(show)(\s+dialog)(\s*{)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#dialog_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(show)\s+(dialog)(\s+([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*"))\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#dialog_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(show|concat)\s+(serial_dialog)(\s+([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*"))?\s*({)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.end.mgs</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#serial_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(rand!|RNG!)\s*(\()</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#script_body</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(json)\s*(\[)</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>punctuation.section.block.begin.mgs</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\]</string>
            <key>name</key>
            <string>punctuation.section.block.end.mgs</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.json</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>include</key>
            <string>#entity_identifier_special</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#boolean_literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#language_constants</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(geometry)\s+(")(%ENTITY_PATH%)(")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(goto)\s+(label|index|script)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(map\s+)?(on_(tick|load|look|interact|command))\s*(!=|==|=)\s*(\$[_a-zA-Z0-9]+)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(map\s+)?(on_(tick|load|look|interact|command))\s*(!=|==|=)\s*([_a-zA-Z][_a-zA-Z0-9]*|"[^"]*")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(map\s+)?(on_(tick|load|look|interact|command))</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.object.property.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(load)\s*(?=map)\b</string>
            <key>name</key>
            <string>keyword.control.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(return|continue|break|goto)\b</string>
            <key>name</key>
            <string>keyword.control.loop.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(command)\s+((\$[_a-zA-Z0-9]+)|([_a-zA-Z][_a-zA-Z0-9]*|(['"])[^`]*?\5))(\s+(fail)|\s*(\+)\s*((\$[_a-zA-Z0-9]+)|([_a-zA-Z][_a-zA-Z0-9]*|(['"])[^`]*?\12)))?\s*((=)\s*((\$[_a-zA-Z0-9]+)|([_a-zA-Z][_a-zA-Z0-9]*|(['"])[^`]*?\18)))?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
              <key>4</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
              <key>6</key>
              <dict>
                <key>name</key>
                <string>variable.language.mgs</string>
              </dict>
              <key>8</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>10</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
              <key>11</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
              <key>14</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
              <key>16</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
              <key>17</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(geometry|map|command|alias|dialog|serial_dialog|entity|flag|variable)\s+(\$[_a-zA-Z0-9]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>variable.other.constant.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(geometry|map|command|alias|dialog|serial_dialog|entity|flag|variable)\s+([_a-zA-Z][_a-zA-Z0-9]*\b|"[^"]*?")</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(index|slot|button|light|dialog|serial_dialog|flag|variable|label)\b</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(origin|length|position|x|y|(primary|secondary)_id|primary_id_type|(current_)?animation|animation_frame|strafe|name|path|direction|type|glitched)\b</string>
            <key>name</key>
            <string>variable.object.property.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(player_control|lights_control|hex_editor|hex_dialog_mode|hex_control|hex_clipboard|serial_control|warp_state|serial_connect|debug_mode)\b</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(delete|(un)?hide|save|load|erase|block|wait|close|(un)?pause|show|copy|fade|shake|show|concat)\b</string>
            <key>name</key>
            <string>storage.type.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(out|in|open|closed|fail|forever|over|down|up|pressed)\b</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(player|self|camera)\b</string>
            <key>name</key>
            <string>variable.language.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>&lt;|&lt;=|!=|==|=&gt;|&gt;|\|\||&amp;&amp;|intersects</string>
            <key>name</key>
            <string>keyword.operator.logical.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(-&gt;|=|\?=|\+=|-=|\*=|\/=|%=|!)</string>
            <key>name</key>
            <string>keyword.operator.assignment.mgs</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constant_literal</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number_literal</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=goto|script)\s+("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*\b)</string>
            <key>name</key>
            <string>entity.name.function.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=(warp_state|type|name|path) (=|==|!=))\s+("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*\b)</string>
            <key>name</key>
            <string>string.quoted.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=label)\s+("[^"]*"|[_a-zA-Z][_a-zA-Z0-9]*\b)</string>
            <key>name</key>
            <string>entity.name.label.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([_a-zA-Z][_a-zA-Z0-9]*)\s*(:)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.label.mgs</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.operator.assignment.mgs</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>[_a-zA-Z][_a-zA-Z0-9]*</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
          <dict>
            <key>match</key>
            <string>[_a-zA-Z][_a-zA-Z0-9]*|"[^"]*"</string>
            <key>name</key>
            <string>variable.parameter.mgs</string>
          </dict>
        </array>
      </dict>
    </dict>
    <key>scopeName</key>
    <string>source.mgs</string>
  </dict>
</plist>